### ISSUE TITLE
How do I build/install/deploy Thunderbit?

### ISSUE THREAD

**Issue by jpgrace** [thunderbit/thunderbit#28]
Hi,

This project looks interesting to me. It looks like it needs a little love, and I may be able to help. There are a few items that I think would instantly make it more accessible to people like me.

- An installation guide
- Screenshots of the product in action in action to quickly determine if this is a solution for the problem I'm trying to solve.

I believe that closing this feedback loop will improve the projects virtuous cycle.

**Comment by rickmclean** [comment]
Hi, thanks for communicating with us. You're welcome to contribute and we'll be very pleased to have your help. My friend @greenled is preparing a quick installation and deploy guide of Thunderbit, as soon as he finishes it will be online.
Meantime you can also check out these two links if you haven't yet: 
https://tree.taiga.io/project/thunderbit/
http://thunderbit.herokuapp.com

**Comment by greenled** [comment]
Hi @jpgrace, and thank you for your interest

I totally agree with you, we are poor in documentation. But the good news are we have plans to solve this soon :) See [#24](https://tree.taiga.io/project/thunderbit/us/24), [#25](https://tree.taiga.io/project/thunderbit/us/25) and [#27](https://tree.taiga.io/project/thunderbit/us/27).

We still don't have a production ready installer, but as a developer you can test it locally or deploy it to the cloud. See beow.

Also, we keep a running instance at http://thunderbit.herokuapp.com which you can play with (user=tbit, password=tbit). It is actually empty: since we added tags support we removed old untagged items, but still have not added new ones. Would be great if you add some tagged content. Don't bother selecting **real** files, as it is using a mock storage module which only stores file name and tags. Right now we are focused on tagging, more than actually storing files, as there are a lot of file storage platforms out there.

As soon as we add tags recommender system we will post screenshots.

Here is a quick guide of how to run a local instance of Thunderbit and how to run it on Heroku. I wrote it in the last hour, so it may have bugs. Just tell us if you get stuck.

## How to run Thunderbit locally

### Install Play Framework

Thunderbit is built with [Play Framework](http://www.playframework.com) 2.4, so the first step is to install it. There are several ways to get this done. For me, the easier one is trough [Lightbend Activator](http://www.playframework.com/download) (used to be Typesafe Activator). You can find installation details at the [Play docs](https://www.playframework.com/documentation/2.4.x/Installing).

Moreover, Play Framewok projects are just [SBT](http://www.scala-sbt.org) projects. So, if you already have SBT, you can just clone the repo and use SBT to run/test/deploy it.

### Get a running MongoDB instance

We use MongoDB to store data. You can set up your own local MongoDB instance, or just get one ready to go (and for free) at [mlab](http://mlab.com)

### Run/Test the application

Once you have set up Play Fremework 2.4 and MongoDB, get Thunderbit's  source code and go to the project's root directory. Once there, edit the configurations file at `con/application.conf` and set the authentication and database connection keys, for example:

```
mongodb.uri="mongodb://127.0.0.1:27017/thunderbit"
authentication.username = "a"
authentication.password = "a"
```

Then, back to the project root directory, run `activator run`, let it resolve dependencies and compile, and then open `http://localhost:9000` in your browser. Now you should have a running instance of Thunderbit.

### Use a different storage backend (optional)

By default, Thunderbit it will use a mock storage module which will receive uploaded files, but will discard them and serve a static mock file. You can change this with `storage.*` configuration keys, for example:

```
storage.type = "local"
# Make sure you have write access to storedFiles
storage.local.path = "storedFiles" 
storage.local.createPath = true
```

Or use your favorite bucket at Amazon S3:

```
storage.type = "s3"
storage.s3.accesskey = "myAccessKey"
storage.s3.secretkey = "mySecretKey"
storage.s3.bucket = "bucketForThunderbit"
storage.s3.createBucket = true
```

## How to deploy Thunderbit to Heroku (one of several ways to do it)

Heroku is an application hosting service with native support for Play Framework (and others). There are other similar services, like Clevercloud, but we have tested Thunderbit only with Heroku. We keep a running instance of Thunderbit at http://thunderbit.herokuapp.com. You can play with it, and you can set up yours too. Here is how:

### Sign up to Heroku

First, you will need a Heroku account (free plan is ok).

### Get a running MongoDB instance

You will need a MongoDB instance to store application data. We recommend you get a free plan from [mlab](http://mlab.com).

### Create a new Heroku app

Jut that, create a new one. You will have to tell Heroku where to find the application source code. So, make a fork of the Thunderbit repo and point your application to it.

### Set environment variables

You will need to tell Heroku where your database is, the user and password it is going to use, and a the secret key used by Play for encryption. Put those values into environment variables at the application settings, for example:

```
SECRET=Q>]i[Nh5>RW]P4lMn9D7v/P^MTFKe5[DNJy<p^D/^EdPdrEF=;FdES>lWMzNOG[Z
MONGO_URI=mongodb://myUser:myPassword@mydatabaseprovider:27017/mythunderbit
USERNAME=a
PASSWORD=a
```

### Start the application

Restart all dynos and navigate to http://yourappname.herokuapp.com.
